# -*- coding: utf-8 -*-
"""Optimum_behavioural

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybEsl-gbvh_RlUqBnG1t1-9FIyzW04h8
"""

!git clone https://github.com/baophamquocbao0502-crypto/Track_2

!ls Track_2

import tensorflow as tf
print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))
print("GPU available:", tf.test.is_gpu_available())

"""Importieren"""

# Bước 2: Clone data + Import thư viện

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd
import os
import ntpath
import random
import cv2
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dropout, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

print("✅ Import xong!")

# Bước 3: Đọc và cân bằng data
data_dir = 'Track_2'

columns = ['center', 'left', 'right', 'steering', 'throttle', 'reverse', 'speed']
data = pd.read_csv(os.path.join(data_dir, 'driving_log.csv'), names=columns)

# Xử lý đường dẫn - chỉ lấy tên file
def path_leaf(path):
    head, tail = ntpath.split(path)
    return tail

data['center'] = data['center'].apply(path_leaf)
data['left']   = data['left'].apply(path_leaf)
data['right']  = data['right'].apply(path_leaf)

print("✅ Tổng data ban đầu:", len(data))

# Cân bằng data
num_bins = 25
samples_per_bin = 400
hist, bins = np.histogram(data['steering'], num_bins)
center_bins = (bins[:-1] + bins[1:]) * 0.5

plt.figure(figsize=(10, 4))
plt.bar(center_bins, hist, width=0.05)
plt.plot((np.min(data['steering']), np.max(data['steering'])), (samples_per_bin, samples_per_bin), color='red', label='Giới hạn')
plt.title('Phân phối steering TRƯỚC khi cân bằng')
plt.legend()
plt.show()

remove_list = []
for j in range(num_bins):
    list_ = []
    for i in range(len(data['steering'])):
        if data['steering'][i] >= bins[j] and data['steering'][i] <= bins[j+1]:
            list_.append(i)
    list_ = shuffle(list_)
    list_ = list_[samples_per_bin:]
    remove_list.extend(list_)

data.drop(data.index[remove_list], inplace=True)
data = data.reset_index(drop=True)

hist2, _ = np.histogram(data['steering'], num_bins)
plt.figure(figsize=(10, 4))
plt.bar(center_bins, hist2, width=0.05)
plt.plot((np.min(data['steering']), np.max(data['steering'])), (samples_per_bin, samples_per_bin), color='red', label='Giới hạn')
plt.title('Phân phối steering SAU khi cân bằng')
plt.legend()
plt.show()

print("✅ Data sau cân bằng:", len(data))

""" Bước 4: Load ảnh và augmentation"""

# Bước 4: Load ảnh và augmentation

# ✅ Fix bug: dùng df thay vì data global
def load_img_steering(datadir, df):
    image_path = []
    steering = []
    for i in range(len(df)):
        indexed_data = df.iloc[i]
        center, left, right = indexed_data[0], indexed_data[1], indexed_data[2]
        image_path.append(os.path.join(datadir, center.strip()))
        steering.append(float(indexed_data[3]))
        image_path.append(os.path.join(datadir, left.strip()))
        steering.append(float(indexed_data[3]) + 0.15)
        image_path.append(os.path.join(datadir, right.strip()))
        steering.append(float(indexed_data[3]) - 0.15)
    return np.asarray(image_path), np.asarray(steering)

image_paths, steerings = load_img_steering(data_dir + '/IMG', data)
print("✅ Total images:", image_paths.shape)
print("✅ Total steerings:", steerings.shape)

# ✅ Train/Valid split
X_train, X_valid, y_train, y_valid = train_test_split(
    image_paths, steerings, test_size=0.2, random_state=6
)
print(f"✅ Train: {len(X_train)} | Valid: {len(X_valid)}")

# ✅ Augmentation (chỉ áp dụng khi train)
def augment_image(img, steering):
     # 1. Zoom
    if np.random.rand() < 0.5:
        scale = np.random.uniform(1.0, 1.3)
        h, w = img.shape[:2]
        M = cv2.getRotationMatrix2D((w/2, h/2), 0, scale)
        img = cv2.warpAffine(img, M, (w, h))
    # Flip ngang
    if np.random.rand() < 0.5:
        img = cv2.flip(img, 1)
        steering = -steering
    # Dịch chuyển ngang
    if np.random.rand() < 0.5:
        tx = np.random.randint(-50, 50)
        steering += tx * 0.002
        M = np.float32([[1, 0, tx], [0, 1, 0]])
        img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
    # Thay đổi độ sáng
    if np.random.rand() < 0.5:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2HSV).astype(float)
        img[:, :, 2] = np.clip(img[:, :, 2] * np.random.uniform(0.4, 1.2), 0, 255)
        img = cv2.cvtColor(img.astype(np.uint8), cv2.COLOR_HSV2RGB)
    # Shadow ngẫu nhiên
    if np.random.rand() < 0.5:
        h, w = img.shape[:2]
        x1, x2 = np.random.randint(0, w, 2)
        mask = np.zeros_like(img)
        pts = np.array([[x1, 0], [x2, h], [0, h], [0, 0]])
        cv2.fillPoly(mask, [pts], (60, 60, 60))
        img = cv2.addWeighted(img, 1, mask, 0.4, 0)
    return img, steering

# ✅ Preprocessing
def img_preprocess(img):
    img = img[60:135, :, :]
    img = cv2.cvtColor(img, cv2.COLOR_RGB2YUV)
    img = cv2.GaussianBlur(img, (3, 3), 0)
    img = cv2.resize(img, (200, 66))
    img = img / 255.0
    return img

# Kiểm tra augmentation trực quan
sample_img = mpimg.imread(X_train[0])
aug_img, _ = augment_image(sample_img.copy(), y_train[0])

fig, axs = plt.subplots(1, 2, figsize=(12, 4))
axs[0].imshow(sample_img)
axs[0].set_title('Ảnh gốc')
axs[1].imshow(aug_img)
axs[1].set_title('Sau augmentation')
plt.show()

print("✅ Augmentation OK!")

"""# Bước 5: Tạo Generator và Model

"""

# Bước 5: Tạo Generator và Model

# ✅ Batch Generator - không load hết RAM, augment on-the-fly
def batch_generator(image_paths, steerings, batch_size=100, is_training=True):
    while True:
        batch_img = []
        batch_st  = []
        idx = np.random.permutation(len(image_paths))
        for i in range(0, len(image_paths) - batch_size + 1, batch_size):
            batch_idx = idx[i:i + batch_size]
            for j in batch_idx:
                img = mpimg.imread(image_paths[j])
                st  = steerings[j]
                if is_training:
                    img, st = augment_image(img, st)
                batch_img.append(img_preprocess(img))
                batch_st.append(st)
            yield (np.array(batch_img), np.array(batch_st))
            batch_img, batch_st = [], []

# ✅ Model cải tiến - Dropout giảm xuống 0.2-0.3
def nvidia_model():
    model = Sequential([
        Conv2D(24, (5,5), strides=(2,2), input_shape=(66,200,3), activation='elu'),
        Conv2D(36, (5,5), strides=(2,2), activation='elu'),
        Conv2D(48, (5,5), strides=(2,2), activation='elu'),
        Conv2D(64, (3,3), activation='elu'),
        Conv2D(64, (3,3), activation='elu'),
        Dropout(0.3),
        Flatten(),
        Dense(100, activation='elu'),
        Dropout(0.2),
        Dense(50, activation='elu'),
        Dropout(0.2),
        Dense(10, activation='elu'),
        Dense(1)
    ])
    model.compile(Adam(learning_rate=0.001), loss='mse')
    return model

model = nvidia_model()
model.summary()

print("✅ Model sẵn sàng!")

"""# Bước 6: Training"""

# Bước 6: Training

batch_size = 100

# Số steps mỗi epoch
steps_per_epoch = len(X_train) // batch_size
validation_steps = len(X_valid) // batch_size

print(f"Steps per epoch: {steps_per_epoch}")
print(f"Validation steps: {validation_steps}")

# ✅ Callbacks - tự động dừng khi không cải thiện
callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=5,                  # dừng nếu 5 epoch liên tiếp không cải thiện
        restore_best_weights=True,   # lấy weights tốt nhất
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,                  # giảm lr xuống một nửa
        patience=3,                  # sau 3 epoch không cải thiện
        min_lr=1e-6,
        verbose=1
    ),
    ModelCheckpoint(
        'best_model.h5',
        monitor='val_loss',
        save_best_only=True,         # chỉ lưu model tốt nhất
        verbose=1
    )
]

# ✅ Train với generator . Fit Generator
history = model.fit(
    batch_generator(X_train, y_train, batch_size, is_training=True),
    steps_per_epoch=steps_per_epoch,
    epochs=50,
    validation_data=batch_generator(X_valid, y_valid, batch_size, is_training=False),
    validation_steps=validation_steps,
    callbacks=callbacks,
    verbose=1
)

print("✅ Training hoàn tất!")
